spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL} #jdbc:postgresql://localhost:5432/user-service
    username: ${SPRING_DATASOURCE_USERNAME} #admin
    password: ${SPRING_DATASOURCE_PASSWORD} #hackme
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false
  sql:
    init:
      platform: postgresql
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  kafka:
    bootstrap-services: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      group-id: email
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
  hateoas:
      use-hal-as-default-json-media-type: false

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    hostname: user-service
    prefer-ip-address: false

logging:
  level:
    com.aston: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  paths-to-match: /api/v1/**
  use-hateoas: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  default-support-form-data: false
  model-and-view-allowed: true
  api-docs:
    enabled: true
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    urls:
      - url: /api-docs
        name: User Service API
  data-rest:
    enabled: false
  actuator:
    enabled: false
